#!/usr/bin/env node
// Regenerates the `:root { ... }` block in src/index.css from the Figma
// design token exports in src/components/Themes/Default/Tokens/*.tokens.json.
//
// Run after re-exporting tokens from Figma: `npm run sync-tokens`
//
// Two token layers exist in the export:
//   - Style.tokens.json   -> raw "_Primitives" color/number ramp (grayscale, brand, etc.)
//   - Colors.tokens.json  -> semantic aliases into the primitives (surface.*, text.*, border.*, icons.*)
//   - Radius.tokens.json  -> corner radius scale (numbers, in px)
//
// The mapping below prefers the semantic layer (Colors.tokens.json) for every
// shadcn CSS variable, since that's what's meant to be consumed downstream.
// The one exception is --border/--input, which the original hand-authored
// theme pinned to the primitive grayscale-300 swatch (#D0D5DD) rather than
// the semantic `border.default` (#EAECF0, used by --sidebar-border instead) —
// kept as-is here to reproduce the existing visual output exactly. Flip
// BORDER_INPUT_SOURCE below to 'semantic' if you'd rather they track
// `border.default` going forward.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const TOKENS_DIR = path.join(root, 'src/components/Themes/Default/Tokens')
const INDEX_CSS = path.join(root, 'src/index.css')

const BORDER_INPUT_SOURCE = 'primitive' // 'primitive' | 'semantic'

function loadTokens(file) {
  return JSON.parse(readFileSync(path.join(TOKENS_DIR, file), 'utf8'))
}

function flatten(obj, prefix = []) {
  const out = new Map()
  for (const [key, value] of Object.entries(obj)) {
    if (value && typeof value === 'object' && '$value' in value) {
      const flatValue = value.$type === 'color' ? value.$value.hex : value.$value
      out.set(prefix.concat(key).join('.'), flatValue)
    } else if (value && typeof value === 'object') {
      for (const [k, v] of flatten(value, prefix.concat(key))) out.set(k, v)
    }
  }
  return out
}

const colors = flatten(loadTokens('Colors.tokens.json'))
const primitives = flatten(loadTokens('Style.tokens.json'))
const radius = flatten(loadTokens('Radius.tokens.json'))

function hex(map, tokenPath) {
  const value = map.get(tokenPath)
  if (!value) throw new Error(`Token not found: ${tokenPath}`)
  return value.toLowerCase()
}

function rem(map, tokenPath) {
  const px = map.get(tokenPath)
  if (px === undefined) throw new Error(`Token not found: ${tokenPath}`)
  return `${px / 16}rem`
}

const borderInputPath = BORDER_INPUT_SOURCE === 'primitive' ? '_colors._grayscale._300' : 'border.default'
const borderInputMap = BORDER_INPUT_SOURCE === 'primitive' ? primitives : colors

// CSS var -> generated value, in the exact order they appear in index.css.
const vars = {
  background: hex(colors, 'surface.default'),
  foreground: hex(colors, 'text.default'),
  card: hex(colors, 'surface.default'),
  'card-foreground': hex(colors, 'text.default'),
  popover: hex(colors, 'surface.default'),
  'popover-foreground': hex(colors, 'text.default'),
  primary: hex(colors, 'surface.brand'),
  'primary-foreground': hex(colors, 'text.inverse'),
  secondary: hex(colors, 'surface.subtle'),
  'secondary-foreground': hex(colors, 'text.default'),
  muted: hex(colors, 'surface.subtle'),
  'muted-foreground': hex(colors, 'text.subtle'),
  accent: hex(colors, 'surface.brand-subtler'),
  'accent-foreground': hex(colors, 'text.brand-bold'),
  destructive: hex(colors, 'text.status.error'),
  border: hex(borderInputMap, borderInputPath),
  input: hex(borderInputMap, borderInputPath),
  ring: hex(colors, 'border.focused'),
  'chart-1': hex(colors, 'border.accent.red'),
  'chart-2': hex(colors, 'border.accent.green'),
  'chart-3': hex(colors, 'border.accent.maroon'),
  'chart-4': hex(colors, 'border.accent.aqua'),
  'chart-5': hex(colors, 'border.accent.gold'),
  radius: rem(radius, 'radius.radius-md'),
  sidebar: hex(colors, 'surface.default'),
  'sidebar-foreground': hex(colors, 'text.default'),
  'sidebar-primary': hex(colors, 'surface.brand'),
  'sidebar-primary-foreground': hex(colors, 'text.inverse'),
  'sidebar-accent': hex(colors, 'surface.subtle'),
  'sidebar-accent-foreground': hex(colors, 'text.default'),
  'sidebar-border': hex(colors, 'border.default'),
  'sidebar-ring': hex(colors, 'border.focused'),
}

const block = [
  ':root {',
  '  /* Figma "Default" theme tokens (src/components/Themes/Default/Tokens) */',
  '  /* Generated by scripts/sync-tokens.mjs — do not hand-edit, re-run the script instead */',
  ...Object.entries(vars).map(([name, value]) => `  --${name}: ${value};`),
  '}',
].join('\n')

const css = readFileSync(INDEX_CSS, 'utf8')
const rootBlockPattern = /:root \{[^}]*\}/
if (!rootBlockPattern.test(css)) {
  throw new Error('Could not find a :root { ... } block in src/index.css')
}
const nextCss = css.replace(rootBlockPattern, block)
writeFileSync(INDEX_CSS, nextCss)

console.log(`Synced ${Object.keys(vars).length} tokens into src/index.css`)
