// Barrel of all registered themes' token values, for apps that consume this
// library's design tokens directly in JS/TS (charts, inline styles, dynamic
// theme pickers, etc). CSS consumers should use src/styles/themes/*.css and
// src/styles/theme-scale.css instead — components themselves only ever read
// the CSS custom properties, never these objects.
//
// Everything under src/tokens/themes/<name>/ is generated by
// scripts/transform-tokens.mjs (`npm run transform-tokens`) — do not hand-edit
// those files. Add a new theme by registering it in that script, then adding
// an entry to `themes` below.
import { theme as defaultTheme } from './themes/default/theme'

export const themes = {
  default: defaultTheme,
} as const

export type ThemeName = keyof typeof themes
export type ThemeTokens = (typeof themes)[ThemeName]

export { defaultTheme }

// Full raw token sets (palette, component states, full radius/spacing/type
// scale) for the default theme, beyond just the shadcn-named subset above.
export * as defaultColors from './themes/default/colors'
export * as defaultComponents from './themes/default/components'
export * as defaultRadius from './themes/default/radius'
export * as defaultSpacing from './themes/default/spacing'
export * as defaultText from './themes/default/text'
